// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAptIa1HqQpicjA-w-G_AmRmVFw3uKLklA',
    appId: '1:962253857523:web:4161873688569d0e590d86',
    messagingSenderId: '962253857523',
    projectId: 'techacademy-8fbd1',
    authDomain: 'techacademy-8fbd1.firebaseapp.com',
    storageBucket: 'techacademy-8fbd1.appspot.com',
    measurementId: 'G-73GWF4WW6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8AenVAvvvZTsfrfqV2YoGiTBaE8tsbCQ',
    appId: '1:962253857523:android:bb412b7f30f2e13f590d86',
    messagingSenderId: '962253857523',
    projectId: 'techacademy-8fbd1',
    storageBucket: 'techacademy-8fbd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkleznBdF_sOPIso7sEn0sSlhyLoTJOWg',
    appId: '1:962253857523:ios:494e5e239f9ecf08590d86',
    messagingSenderId: '962253857523',
    projectId: 'techacademy-8fbd1',
    storageBucket: 'techacademy-8fbd1.appspot.com',
    iosBundleId: 'com.example.techAcadmy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkleznBdF_sOPIso7sEn0sSlhyLoTJOWg',
    appId: '1:962253857523:ios:494e5e239f9ecf08590d86',
    messagingSenderId: '962253857523',
    projectId: 'techacademy-8fbd1',
    storageBucket: 'techacademy-8fbd1.appspot.com',
    iosBundleId: 'com.example.techAcadmy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAptIa1HqQpicjA-w-G_AmRmVFw3uKLklA',
    appId: '1:962253857523:web:c182fba49a932cd2590d86',
    messagingSenderId: '962253857523',
    projectId: 'techacademy-8fbd1',
    authDomain: 'techacademy-8fbd1.firebaseapp.com',
    storageBucket: 'techacademy-8fbd1.appspot.com',
    measurementId: 'G-772M9YPXR3',
  );
}
